### ISSUE TITLE
[공지] 5월 3일 정상수업진행합니다.

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.DataStructure#16]
내일만나요.

엠티참가자 공결처리가능합니다.
이메일주세요.

**Comment by healust** [comment]
안녕하세요. 교수님
자료구조 수업을 듣고 있는 배한욱이라는 학생입니다. 다름이 아니라 이번 주 금요일이 개교기념일이라 수업이 없는 줄 알고 지방에 있는
본가로 내려왔습니다. 방금 정상 수업 공지 메일 보고 문의 메일 드립니다. 출석을 어떻게 해야하는 지 궁금합니다.

2019년 5월 2일 (목) 오후 6:29, Yukyung Choi <notifications@github.com>님이 작성:

**Comment by unizard** [comment]
@healust 다음 주 수업시간에 이야기 나누시죠.
