### ISSUE TITLE
[공유] Dannis Hong 교수님 한국 방문

### ISSUE THREAD

**Issue by unizard** [unizard/2019.Spring.DataStructure#28]
관심있는 친구들 방문해보시죠.

<img width="513" alt="스크린샷 2019-05-11 오후 6 06 28" src="https://user-images.githubusercontent.com/11758940/57567652-87a02500-7417-11e9-9992-c4bbb71c5154.png">

> http://www.joongboo.com/news/articleView.html?idxno=1350088

**Comment by unizard** [comment]
@All 참여를 희망하는 학생의 경우, 공결처리 해드립니다.

**Comment by healust** [comment]
안녕하세요. 자료구조 수업을 듣고 있는 배한욱이라는 학생입니다.

>

**Comment by healust** [comment]
안녕하세요. 자료구조 수업을 듣고 있는 배한욱이라는 학생입니다.
보내주신 강연 읽고 문의 메일 보냅니다.
정말 꼭 참여하고 싶어서 그런데, 공결 처리 가능할까요?

2019년 5월 13일 (월) 오후 10:32, 열심히공부하자 <forstudydday@gmail.com>님이 작성:

> 안녕하세요. 자료구조 수업을 듣고 있는 배한욱이라는 학생입니다.
>
>>

**Comment by unizard** [comment]
@healust 네 가능합니다. 내일 수업시간에 찾아오세요.
